# Generated by Django 4.0.3 on 2022-03-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(upload_to='event_images/', verbose_name='фото')),
                ('event_text', models.CharField(max_length=300, verbose_name='описание')),
            ],
        ),
    ]
